function present_instructions(q1,q2,freq)

global task_version
global window
global rsize
global rwith
global xCenter
global yCenter
global target
global fsize
global lspace

%% stimulus

shiftstim = -200;

baseRect = [0 0 rsize rsize];
centRect = [0 0 rsize-rwith*2 rsize-rwith*2];

centeredBaseRect = CenterRectOnPointd(baseRect, xCenter, yCenter-shiftstim);
centeredCentRect = CenterRectOnPointd(centRect, xCenter, yCenter-shiftstim);
centeredTarg     = CenterRectOnPointd(target, xCenter-((rsize/2-rwith/2)*1), yCenter-shiftstim);


%%

    [nx, ny] = DrawFormattedText(window, ['Welcome to the task! \n\n' ...
        '(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);

KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['In the task you are asked to detect \n' ...
        'an `opening` in a square. \n' ...
        'The square looks like this. \n' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);

KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['In the task you are asked to detect \n' ...
        'an `opening` in a square. \n' ...
        'The square looks like this. \n' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);

    Screen('FillRect', window, [1 1 1], centeredBaseRect); %base box
    Screen('FillRect', window, [0 0 0], centeredCentRect); %center box
    %     Screen('FillRect', window, coh, centeredTarg); %target
    Screen('DrawDots', window, [xCenter yCenter-shiftstim],fsize,[1 1 1],[0 0],1); %fixation
    Screen('Flip', window);

KbStrokeWait; %wait for a button press


    [nx, ny] = DrawFormattedText(window, ['Your job is to respond \n' ...
        'as soon as possible when you see \n' ...
        'the opening. \n' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);

    Screen('FillRect', window, [1 1 1], centeredBaseRect); %base box
    Screen('FillRect', window, [0 0 0], centeredCentRect); %center box
    %     Screen('FillRect', window, coh, centeredTarg); %target
    Screen('DrawDots', window, [xCenter yCenter-shiftstim],fsize,[1 1 1],[0 0],1); %fixation
    Screen('Flip', window);

    
KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['The opening looks \n' ...
        'like this (it can be on the left \n' ...
        'or on the right): \n'] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);

    Screen('FillRect', window, [1 1 1], centeredBaseRect); %base box
    Screen('FillRect', window, [0 0 0], centeredCentRect); %center box
    Screen('FillRect', window, [.4 .4 .4], centeredTarg); %target
    Screen('DrawDots', window, [xCenter yCenter-shiftstim],fsize,[1 1 1],[0 0],1); %fixation
    Screen('Flip', window);

KbStrokeWait; %wait for a button press

if task_version == 1 %instructions for detection
    [nx, ny] = DrawFormattedText(window, ['When you see the opening\n' ...
        'appear, press the space bar \n' ...
        'as fast as possible\n' ...
        'with your right hand!\n' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
else %instructions for discrimination
    [nx, ny] = DrawFormattedText(window, ['When you see the opening \n' ...
        'appear on the left, press \n' ...
        'the left CTRL key with your left hand. \n' ...
        'When you see the opening \n' ...
        'appear on the right, press \n' ...
        'the right CTRL key with your right hand. \n' ...
        'Please respond as fast as possible!' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);    
end
    
KbStrokeWait; %wait for a button press
    
    [nx, ny] = DrawFormattedText(window, ['The opening can appear \n' ...
        'after a *short* or after a *long* delay.' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);

KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['To help you respond \n' ...
        'as fast as possible, you will\n' ...
        'hear a short tone. This tone\n' ...
        'will help you detect *when*\n' ...
        'the opening will appear.' ...
        '\n\n(press a button to continue)' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);

KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['The following tone (press to listen) \n' ...
        'indicates that the opening will \n' ...
        'probably appear after a\n' ...
        '*short* delay.\n' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
    KbStrokeWait; %wait for a button press

    pahandle = PsychPortAudio('Open', [], [], 0, freq, 2);
    PsychPortAudio('FillBuffer', pahandle, q1);
    PsychPortAudio('Start', pahandle, 1, 0, 1);
    PsychPortAudio('Close', pahandle);
    
KbStrokeWait

    [nx, ny] = DrawFormattedText(window, ['The following tone (press to listen) \n' ...
        'indicates that the opening will \n' ...
        'probably appear after a\n' ...
        '*long* delay.\n' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
    KbStrokeWait; %wait for a button press

    pahandle = PsychPortAudio('Open', [], [], 0, freq, 2);
    PsychPortAudio('FillBuffer', pahandle, q2);
    PsychPortAudio('Start', pahandle, 1, 0, 1);
    PsychPortAudio('Close', pahandle);
    
KbStrokeWait

    [nx, ny] = DrawFormattedText(window, ['Again. *Short* delay: ' ...
        '(press to listen) \n' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
    KbStrokeWait; %wait for a button press

    pahandle = PsychPortAudio('Open', [], [], 0, freq, 2);
    PsychPortAudio('FillBuffer', pahandle, q1);
    PsychPortAudio('Start', pahandle, 1, 0, 1);
    PsychPortAudio('Close', pahandle);

KbStrokeWait

    [nx, ny] = DrawFormattedText(window, ['Again. *Long* delay: ' ...
        '(press to listen) \n' ...
        ] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
    KbStrokeWait; %wait for a button press

    pahandle = PsychPortAudio('Open', [], [], 0, freq, 2);
    PsychPortAudio('FillBuffer', pahandle, q2);
    PsychPortAudio('Start', pahandle, 1, 0, 1);
    PsychPortAudio('Close', pahandle);
    
KbStrokeWait

    [nx, ny] = DrawFormattedText(window, ['On some trials, the opening won`t \n' ...
        'appear at all. It is important that \n' ...
        'you do not respond in that case.' ...
        '\n\n(press a button to continue)'] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
KbStrokeWait; %wait for a button press

    [nx, ny] = DrawFormattedText(window, ['One last thing. \n' ...
        'Please keep your eyes on the dot in \n' ...
        'the middle at all times.\n' ...
        'So do not move your eyes to\n' ...
        'the opening when you see it, but.\n' ...
        'keep looking at the middle.\n' ...
        '\n\n(press a button to continue)'] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
KbStrokeWait

    [nx, ny] = DrawFormattedText(window, ['Now let`s practice for a bit!\n' ...
        'Remember, the tone will help \n' ...
        'you anticipate when the opening\n' ...
        'will appear! So please use the\n' ...
        'tone to do the task!' ...
        '\n\n(press a button to continue)'] ...
        , 'center', 'center', 1,[0 0 0],[],[],lspace);
    Screen('DrawText', window, ' ', nx, ny, [255, 0, 0, 255]);
    Screen('Flip',window);
    
KbStrokeWait


end
